[package]
name = "rip_token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
dashmap = "5.4.0"
counter = "0.5.7"
num-format = "0.4.4"

[profile.release]
lto = "fat"
codegen-units = 1