[package]
name = "rip_token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
dashmap = "5.5.0"
num-format = "0.4.4"
rand = "0.8.5"

[profile.release]
lto = "fat"
codegen-units = 1